name: Playwright Tests.OTAI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

  upload-reports:
    name: Upload Reports
    needs: e2e-tests
    runs-on: ubuntu-latest

    steps:
      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Install Java and Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless
          npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report HTML
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Display downloaded report files
        run: ls -R
